Rotation special objects
SL-GAME/SansLogiqueGame pull request #306
Opened 2023-06-10 17:59 UTC by Matda43

2023-06-11 15:04 UTC, Savro01 submitted a review, later dismissed

2023-06-12 16:31 UTC, adrimyla requested changes
- C'est l'idée et pour la manette et les puzzle c'est parfait
- Par contre il faudrait incliner un peu le mannequin pour qu'il flotte et ne tourne pas "tout droit"
- Enfin, ça serait cool de d'ajouter une espèce "d'aura" autour des objets pour les voir de loin (à voir si on fait ça dans une PR à part ou non)

2023-06-12 18:54 UTC, adrimyla commented
- Au lieu d'une aura > mettre un material emmissive qui se désactive quad on récupère le pouvoir

2023-07-03 17:22 UTC, adrimyla approved these changes

2023-07-03 17:22 UTC, merged