Création biomes désert + création énigme forêt de nuit
SL-GAME/SansLogiqueGame pull request #313
Opened 2023-06-12 18:17 UTC by Lisouille69

2023-06-20 15:53 UTC, HugoPasquier commented
Pour le désert, le LD est vraiment trop cool, on a vraiment l'impression d'être plongé dans un mini-open world avec une vibe entre God of War Ragnarok et Journey. Le seul truc qui me dérange, c'est la taille de l'émetteur et du "miroir" des lasers. Dans l'idée c'est cool d'avoir des assets de cette taille pour le sentiment de vertige que ça peut procurer. Mais j'ai peur qu'il y ai un effet pétard mouillé quand on croisera les même assets à notre hauteur plus tard dans le jeu. Je pense  qu'on peut juste garder les grandes plateformes, tout en réduisant la taille des éléments laser pour les faire coller à ceux que l'on retrouve dans le Monde Abstrait.

Sinon pour la cover de la grotte, ça ajoute un peu de relief, c'est cool.
Et J'attends de voir ce que vous allez faire avec la crypte de la forêt de Nuit.

2023-06-22 17:16 UTC, adrimyla commented
# Review du LD
## La partie monde abstrait

- Comme Hugo, je trouve que les assets géants ne rendent pas super bien. Pour ceux de la grotte ça passe un peu mieux mais c'est vrai que les émetteus/transmetteurs sont vraiment géants. Je pense qu'il faut garder à l'idée que c'est un avant goût de la suite mais pas "la grande découverte" de ce niveau.
- Pour la position du laser : je comprends pas trop comment on peut le diriger dans le récepteur ? L'emetteur ne vise pas le transmetteur 🤔 
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/ce1f892a-512e-43f1-b895-63b3f69e4c2a)
- Je suis pas trop pour le faire de poser le robot miroir de façon inclinée, pourquoi ne pas le mettre à plat ou a moitié ensablé ? (surtout que le dessous des pattes est transparent) 
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/3b566217-47ed-48af-aa33-c78e7e157f96)
Exemple : 
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/7dc12090-ea48-439a-9626-0cd28cc1dd07)

## La partie grotte
- RAS

## La partie forêt
- Pour la vanne à récupérer il y en a normalement une dans les dossiers que j'avais créé au moment où il fallait en poser une sur la machine. On peut la réutiliser avec son système : Content/Levels/SubLevels/Forest/Blueprints/Machine/BP_ValveKey.uasset
- 
## Autre
- Il faudra ajouter les tuyaux, peut être que @Matda43 peut le faire ? :)
- J'ai pas vraiment compris où sont les différents morceaux de porte ?
- Pour le pilier sous le mannequin, reprendre le celui de la manette : Content/Levels/SubLevels/Grotte/Hall/BP_StoneUnderController.uasset

2023-06-22 17:32 UTC, adrimyla requested changes
Voir review ci-dessus

2023-06-27 16:14 UTC, adrimyla approved these changes

2023-06-27 16:14 UTC, merged