Change pipes mesh + materials (hall - forest)
SL-GAME/SansLogiqueGame pull request #316
Opened 2023-06-17 20:26 UTC by Matda43

2023-06-18 12:49 UTC, Savro01 approved these changes, later dismissed

2023-06-22 18:02 UTC, adrimyla reviewed
De mon côté les textures ne chargent pas ni en viewport, ni en build. Est-ce que vous aviez eu ce problème ? 
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/8db68f21-f055-4278-a92c-df23aba5bd0e)

2023-06-22 18:03 UTC, adrimyla requested changes
De mon côté les textures ne chargent pas ni en viewport, ni en build. Est-ce que vous aviez eu ce problème ? 
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/8db68f21-f055-4278-a92c-df23aba5bd0e)

2023-06-26 19:56 UTC, adrimyla commented
- Les normales semblent être inversées : je m'occuperai de corriger ça
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/31547dc3-73ca-43ec-abb2-ac4d4becba5c)
- J'ajouterai également un contour un peu plus présent autour du verre car là c'est très transparent.

2023-06-29 18:53 UTC, adrimyla approved these changes

2023-06-29 18:53 UTC, merged