Fermeture de l'encadré avec clic droit/echap
SL-GAME/SansLogiqueGame pull request #347
Opened 2023-07-20 17:55 UTC by Savro01

2023-07-20 18:35 UTC, Savro01 commented
J'ai profiter de toucher MainCharacter pour régler le bug du clic droit 

Et j'ai également fait en sorte que quand on zoom sur une image (les indices), si on fait clic droit ca dezoom

2023-07-21 17:31 UTC, adrimyla requested changes
### Ce qui va
- La fermeture de l'encadré avec clic droit : OK
- La fermeture du carnet avec clic droit : OK
- Le clic droit pour récupérer le mannequin : OK

### Ce qui va pas
- Lorsque l'encadré est ouvert, si on clique sur J, alors le carnet se ferme mais pas l'encadré

https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/2bd61a71-ceb5-40b3-953f-b7864fb3a8d2

2023-07-24 16:18 UTC, adrimyla requested changes
Ok pour l'encadré qui se ferme bien quand on appuie sur J !

Par contre j'ai remarqué un dernier bug : quand on ouvre le carnet avec J, qu'on va dans l'onglet indices, qu'on clic sur l'image d'un indice pour l'agrandir, qu'on clic sur un autre onglet du carnet, qu'on ferme le carnet, qu'on l'ouvre à nouveau et qu'on retourne sur la page des indices, l'indice reste affiché en grand.

Bon ok c'est alambiqué mais à voir si c'est pas juste un petit truc à cocher ^^

https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/df55b849-9fea-49d9-817a-5ae0fd480aef

2023-07-28 15:41 UTC, adrimyla approved these changes

2023-07-28 15:41 UTC, merged