Translation setup
SL-GAME/SansLogiqueGame pull request #378
Opened 2023-08-19 09:28 UTC by Nicovi15

2023-08-19 09:29 UTC, Nicovi15 commented
En attente du merge de https://github.com/SL-GAME/SansLogiqueGame/pull/376, pour appliquer la traduction aux objets inspectables.

2023-08-30 17:09 UTC, adrimyla requested changes
C'est presque bon! Il y a juste quelques petits soucis : 

- La toute première page du carnet ne semble pas traduite ni en italien ni en espagnol. 
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/b650b1db-4dac-42e6-bf26-74b8713ed20c)

![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/0d3d0f51-f110-4387-9ae2-cf5a38ecdd7f)

- Quand on revient dans le menu après avoir changé de langue la case de sélection est blanche comme si rien n'est sélectionné (c'est pas super grave mais c'est bizarre)
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/accc0e16-7164-4f36-a496-d95ca2af9788)

- Le texte dépasse un peu dans le menu (pareil si c'est chiant a modifier, tant pis)
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/e0fb3431-50da-402d-b9c0-729f4d28227a)

Lien vers la build : https://fromsmash.com/apkYqNYsGQ-ct

2023-08-30 17:37 UTC, adrimyla commented
C'est presque bon! Il y a juste quelques petits soucis : 

- La toute première page du carnet ne semble pas traduite ni en italien ni en espagnol. 
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/b650b1db-4dac-42e6-bf26-74b8713ed20c)

![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/0d3d0f51-f110-4387-9ae2-cf5a38ecdd7f)

- Quand on revient dans le menu après avoir changé de langue la case de sélection est blanche comme si rien n'est sélectionné (c'est pas super grave mais c'est bizarre)
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/accc0e16-7164-4f36-a496-d95ca2af9788)

- Le texte dépasse un peu dans le menu (pareil si c'est chiant a modifier, tant pis)
![image](https://github.com/SL-GAME/SansLogiqueGame/assets/57765484/e0fb3431-50da-402d-b9c0-729f4d28227a)

2023-08-31 16:27 UTC, Nicovi15 commented
Normalement, j'ai corrigé toutes les retakes.

2023-08-31 16:58 UTC, adrimyla approved these changes

2023-08-31 16:58 UTC, merged